# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import product_receiver_pb2 as product__receiver__pb2


class ProductReceiverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProductFromReceiver = channel.unary_unary(
                '/product_receiver.ProductReceiverService/CreateProductFromReceiver',
                request_serializer=product__receiver__pb2.CreateProductFromReceiverRequest.SerializeToString,
                response_deserializer=product__receiver__pb2.CreateProductFromReceiverResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/product_receiver.ProductReceiverService/Update',
                request_serializer=product__receiver__pb2.UpdateByIdRequest.SerializeToString,
                response_deserializer=product__receiver__pb2.UpdateByIdResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/product_receiver.ProductReceiverService/Delete',
                request_serializer=product__receiver__pb2.DeleteByIdRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ProductReceiverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProductFromReceiver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductReceiverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProductFromReceiver': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProductFromReceiver,
                    request_deserializer=product__receiver__pb2.CreateProductFromReceiverRequest.FromString,
                    response_serializer=product__receiver__pb2.CreateProductFromReceiverResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=product__receiver__pb2.UpdateByIdRequest.FromString,
                    response_serializer=product__receiver__pb2.UpdateByIdResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=product__receiver__pb2.DeleteByIdRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product_receiver.ProductReceiverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProductReceiverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProductFromReceiver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product_receiver.ProductReceiverService/CreateProductFromReceiver',
            product__receiver__pb2.CreateProductFromReceiverRequest.SerializeToString,
            product__receiver__pb2.CreateProductFromReceiverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product_receiver.ProductReceiverService/Update',
            product__receiver__pb2.UpdateByIdRequest.SerializeToString,
            product__receiver__pb2.UpdateByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/product_receiver.ProductReceiverService/Delete',
            product__receiver__pb2.DeleteByIdRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
