# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduct.proto\x12\x07product\"B\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\x12\r\n\x05likes\x18\x04 \x01(\x03\" \n\x12LikeProductRequest\x12\n\n\x02id\x18\x01 \x01(\t\"8\n\x13LikeProductResponse\x12!\n\x07product\x18\x01 \x01(\x0b\x32\x10.product.Product2\\\n\x0eProductService\x12J\n\x0bLikeProduct\x12\x1b.product.LikeProductRequest\x1a\x1c.product.LikeProductResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCT._serialized_start=26
  _PRODUCT._serialized_end=92
  _LIKEPRODUCTREQUEST._serialized_start=94
  _LIKEPRODUCTREQUEST._serialized_end=126
  _LIKEPRODUCTRESPONSE._serialized_start=128
  _LIKEPRODUCTRESPONSE._serialized_end=184
  _PRODUCTSERVICE._serialized_start=186
  _PRODUCTSERVICE._serialized_end=278
# @@protoc_insertion_point(module_scope)
