# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product_receiver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16product_receiver.proto\x12\x10product_receiver\x1a\x1bgoogle/protobuf/empty.proto\"C\n\x0fProductReceiver\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\t\"_\n CreateProductFromReceiverRequest\x12;\n\x10product_receiver\x18\x01 \x01(\x0b\x32!.product_receiver.ProductReceiver\"`\n!CreateProductFromReceiverResponse\x12;\n\x10product_receiver\x18\x01 \x01(\x0b\x32!.product_receiver.ProductReceiver\"P\n\x11UpdateByIdRequest\x12;\n\x10product_receiver\x18\x01 \x01(\x0b\x32!.product_receiver.ProductReceiver\"Q\n\x12UpdateByIdResponse\x12;\n\x10product_receiver\x18\x01 \x01(\x0b\x32!.product_receiver.ProductReceiver\"\'\n\x11\x44\x65leteByIdRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t2\xc1\x02\n\x16ProductReceiverService\x12\x86\x01\n\x19\x43reateProductFromReceiver\x12\x32.product_receiver.CreateProductFromReceiverRequest\x1a\x33.product_receiver.CreateProductFromReceiverResponse\"\x00\x12U\n\x06Update\x12#.product_receiver.UpdateByIdRequest\x1a$.product_receiver.UpdateByIdResponse\"\x00\x12G\n\x06\x44\x65lete\x12#.product_receiver.DeleteByIdRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_receiver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRODUCTRECEIVER._serialized_start=73
  _PRODUCTRECEIVER._serialized_end=140
  _CREATEPRODUCTFROMRECEIVERREQUEST._serialized_start=142
  _CREATEPRODUCTFROMRECEIVERREQUEST._serialized_end=237
  _CREATEPRODUCTFROMRECEIVERRESPONSE._serialized_start=239
  _CREATEPRODUCTFROMRECEIVERRESPONSE._serialized_end=335
  _UPDATEBYIDREQUEST._serialized_start=337
  _UPDATEBYIDREQUEST._serialized_end=417
  _UPDATEBYIDRESPONSE._serialized_start=419
  _UPDATEBYIDRESPONSE._serialized_end=500
  _DELETEBYIDREQUEST._serialized_start=502
  _DELETEBYIDREQUEST._serialized_end=541
  _PRODUCTRECEIVERSERVICE._serialized_start=544
  _PRODUCTRECEIVERSERVICE._serialized_end=865
# @@protoc_insertion_point(module_scope)
