# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"\x1d\n\x0fGetUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\"\x10\n\x0eGetUserRequest2G\n\x0bUserService\x12\x38\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETUSERRESPONSE._serialized_start=20
  _GETUSERRESPONSE._serialized_end=49
  _GETUSERREQUEST._serialized_start=51
  _GETUSERREQUEST._serialized_end=67
  _USERSERVICE._serialized_start=69
  _USERSERVICE._serialized_end=140
# @@protoc_insertion_point(module_scope)
